/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreprojectLogoDiscord {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectLogoFigma {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectLogoGithub {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectLogoReddit {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeAirplay {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeAlertTriangle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeAlign {
        "_style": string;
        "height": string | number;
        "variant": "center" | "justify" | "left" | "right";
        "width": string | number;
    }
    interface CoreprojectShapeArrow {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeAtSign {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeAward {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeBarChart {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeBell {
        "_style": string;
        "height": string | number;
        "variant": "on" | "off";
        "width": string | number;
    }
    interface CoreprojectShapeBook {
        "_style": string;
        "height": string | number;
        "variant": "open" | "close";
        "width": string | number;
    }
    interface CoreprojectShapeBox {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCalendar {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCast {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCheck {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeChevron {
        "_style": string;
        "height": string | number;
        "variant": "up" | "right" | "down" | "left";
        "width": string | number;
    }
    interface CoreprojectShapeChevrons {
        "_style": string;
        "height": string | number;
        "variant": "up" | "right" | "down" | "left";
        "width": string | number;
    }
    interface CoreprojectShapeCircle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeClipboard {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeClock {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCloudOff {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCode {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCompass {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCopy {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeCorner {
        "_style": string;
        "height": string | number;
        "variant": "down-right" | "down-left" | "left-down" | "left-up" | "up-left" | "up-right" | "right-up" | "right-down";
        "width": string | number;
    }
    interface CoreprojectShapeDelete {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeDice {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeDownload {
        "_style": string;
        "height": string | number;
        "variant": "arrow" | "cloud";
        "width": string | number;
    }
    interface CoreprojectShapeEdit {
        "_style": string;
        "height": string | number;
        "variant": "box" | "pencil" | "line-with-pencil";
        "width": string | number;
    }
    interface CoreprojectShapeExpand {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeExternalLink {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeEye {
        "_style": string;
        "height": string | number;
        "variant": "open" | "close";
        "width": string | number;
    }
    interface CoreprojectShapeFastForward {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeFile {
        "_style": string;
        "height": string | number;
        "variant": "normal" | "minus" | "plus" | "text";
        "width": string | number;
    }
    interface CoreprojectShapeFilter {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeFlag {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeFolder {
        "_style": string;
        "height": string | number;
        "variant": "normal" | "minus" | "plus";
        "width": string | number;
    }
    interface CoreprojectShapeForum {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeFrown {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeGift {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeGlobe {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeGrid {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHardDrive {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHash {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHeadphones {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHeart {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHelpCircle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeHome {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeInfo {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeKey {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeLink {
        "_style": string;
        "height": string | number;
        "variant": "tilted" | "horizontal";
        "width": string | number;
    }
    interface CoreprojectShapeList {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeLock {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeLogIn {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeLogOut {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeLogo {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMail {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMapPin {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMaximize {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMeh {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMessageCircle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMinimize {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMinus {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMonitor {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMoon {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMore {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMousePointer {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeMove {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapePause {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapePauseCircle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapePlay {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapePlayCircle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapePlus {
        "_style": string;
        "height": string | number;
        "variant": "no-border" | "circle" | "square";
        "width": string | number;
    }
    interface CoreprojectShapePreferences {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeRefresh {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeRepeat {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeRotate {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSave {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSearch {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSettings {
        "_style": string;
        "height": string | number;
        "variant": "outline" | "filled";
        "width": string | number;
    }
    interface CoreprojectShapeShare {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeShield {
        "_style": string;
        "height": string | number;
        "variant": "on" | "off";
        "width": string | number;
    }
    interface CoreprojectShapeShoppingCart {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeShrink {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSmartphone {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSmile {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSpeaker {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeStar {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeSun {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeTag {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeTerminal {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeThumbs {
        "_style": string;
        "height": string | number;
        "variant": "up" | "down";
        "width": string | number;
    }
    interface CoreprojectShapeToggle {
        "_style": string;
        "height": string | number;
        "variant": "off" | "on";
        "width": string | number;
    }
    interface CoreprojectShapeTool {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeTrash {
        "_style": string;
        "height": string | number;
        "variant": "with-lines" | "without-lines";
        "width": string | number;
    }
    interface CoreprojectShapeTrending {
        "_style": string;
        "height": string | number;
        "variant": "up" | "down";
        "width": string | number;
    }
    interface CoreprojectShapeTriangle {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeTwitter {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeType {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeUnderline {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeUnlock {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeUpload {
        "_style": string;
        "height": string | number;
        "variant": "arrow" | "cloud";
        "width": string | number;
    }
    interface CoreprojectShapeUser {
        "_style": string;
        "height": string | number;
        "variant": "normal" | "check" | "minus" | "plus" | "x";
        "width": string | number;
    }
    interface CoreprojectShapeUsers {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeVolume {
        "_style": string;
        "height": string | number;
        "variant": "off" | "half" | "full" | "mute";
        "width": string | number;
    }
    interface CoreprojectShapeX {
        "_style": string;
        "height": string | number;
        "variant": "no-border" | "circle" | "octagon" | "square";
        "width": string | number;
    }
    interface CoreprojectShapeZapOff {
        "_style": string;
        "height": string | number;
        "width": string | number;
    }
    interface CoreprojectShapeZoom {
        "_style": string;
        "height": string | number;
        "variant": "in" | "out";
        "width": string | number;
    }
}
declare global {
    interface HTMLCoreprojectLogoDiscordElement extends Components.CoreprojectLogoDiscord, HTMLStencilElement {
    }
    var HTMLCoreprojectLogoDiscordElement: {
        prototype: HTMLCoreprojectLogoDiscordElement;
        new (): HTMLCoreprojectLogoDiscordElement;
    };
    interface HTMLCoreprojectLogoFigmaElement extends Components.CoreprojectLogoFigma, HTMLStencilElement {
    }
    var HTMLCoreprojectLogoFigmaElement: {
        prototype: HTMLCoreprojectLogoFigmaElement;
        new (): HTMLCoreprojectLogoFigmaElement;
    };
    interface HTMLCoreprojectLogoGithubElement extends Components.CoreprojectLogoGithub, HTMLStencilElement {
    }
    var HTMLCoreprojectLogoGithubElement: {
        prototype: HTMLCoreprojectLogoGithubElement;
        new (): HTMLCoreprojectLogoGithubElement;
    };
    interface HTMLCoreprojectLogoRedditElement extends Components.CoreprojectLogoReddit, HTMLStencilElement {
    }
    var HTMLCoreprojectLogoRedditElement: {
        prototype: HTMLCoreprojectLogoRedditElement;
        new (): HTMLCoreprojectLogoRedditElement;
    };
    interface HTMLCoreprojectShapeAirplayElement extends Components.CoreprojectShapeAirplay, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeAirplayElement: {
        prototype: HTMLCoreprojectShapeAirplayElement;
        new (): HTMLCoreprojectShapeAirplayElement;
    };
    interface HTMLCoreprojectShapeAlertTriangleElement extends Components.CoreprojectShapeAlertTriangle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeAlertTriangleElement: {
        prototype: HTMLCoreprojectShapeAlertTriangleElement;
        new (): HTMLCoreprojectShapeAlertTriangleElement;
    };
    interface HTMLCoreprojectShapeAlignElement extends Components.CoreprojectShapeAlign, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeAlignElement: {
        prototype: HTMLCoreprojectShapeAlignElement;
        new (): HTMLCoreprojectShapeAlignElement;
    };
    interface HTMLCoreprojectShapeArrowElement extends Components.CoreprojectShapeArrow, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeArrowElement: {
        prototype: HTMLCoreprojectShapeArrowElement;
        new (): HTMLCoreprojectShapeArrowElement;
    };
    interface HTMLCoreprojectShapeAtSignElement extends Components.CoreprojectShapeAtSign, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeAtSignElement: {
        prototype: HTMLCoreprojectShapeAtSignElement;
        new (): HTMLCoreprojectShapeAtSignElement;
    };
    interface HTMLCoreprojectShapeAwardElement extends Components.CoreprojectShapeAward, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeAwardElement: {
        prototype: HTMLCoreprojectShapeAwardElement;
        new (): HTMLCoreprojectShapeAwardElement;
    };
    interface HTMLCoreprojectShapeBarChartElement extends Components.CoreprojectShapeBarChart, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeBarChartElement: {
        prototype: HTMLCoreprojectShapeBarChartElement;
        new (): HTMLCoreprojectShapeBarChartElement;
    };
    interface HTMLCoreprojectShapeBellElement extends Components.CoreprojectShapeBell, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeBellElement: {
        prototype: HTMLCoreprojectShapeBellElement;
        new (): HTMLCoreprojectShapeBellElement;
    };
    interface HTMLCoreprojectShapeBookElement extends Components.CoreprojectShapeBook, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeBookElement: {
        prototype: HTMLCoreprojectShapeBookElement;
        new (): HTMLCoreprojectShapeBookElement;
    };
    interface HTMLCoreprojectShapeBoxElement extends Components.CoreprojectShapeBox, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeBoxElement: {
        prototype: HTMLCoreprojectShapeBoxElement;
        new (): HTMLCoreprojectShapeBoxElement;
    };
    interface HTMLCoreprojectShapeCalendarElement extends Components.CoreprojectShapeCalendar, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCalendarElement: {
        prototype: HTMLCoreprojectShapeCalendarElement;
        new (): HTMLCoreprojectShapeCalendarElement;
    };
    interface HTMLCoreprojectShapeCastElement extends Components.CoreprojectShapeCast, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCastElement: {
        prototype: HTMLCoreprojectShapeCastElement;
        new (): HTMLCoreprojectShapeCastElement;
    };
    interface HTMLCoreprojectShapeCheckElement extends Components.CoreprojectShapeCheck, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCheckElement: {
        prototype: HTMLCoreprojectShapeCheckElement;
        new (): HTMLCoreprojectShapeCheckElement;
    };
    interface HTMLCoreprojectShapeChevronElement extends Components.CoreprojectShapeChevron, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeChevronElement: {
        prototype: HTMLCoreprojectShapeChevronElement;
        new (): HTMLCoreprojectShapeChevronElement;
    };
    interface HTMLCoreprojectShapeChevronsElement extends Components.CoreprojectShapeChevrons, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeChevronsElement: {
        prototype: HTMLCoreprojectShapeChevronsElement;
        new (): HTMLCoreprojectShapeChevronsElement;
    };
    interface HTMLCoreprojectShapeCircleElement extends Components.CoreprojectShapeCircle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCircleElement: {
        prototype: HTMLCoreprojectShapeCircleElement;
        new (): HTMLCoreprojectShapeCircleElement;
    };
    interface HTMLCoreprojectShapeClipboardElement extends Components.CoreprojectShapeClipboard, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeClipboardElement: {
        prototype: HTMLCoreprojectShapeClipboardElement;
        new (): HTMLCoreprojectShapeClipboardElement;
    };
    interface HTMLCoreprojectShapeClockElement extends Components.CoreprojectShapeClock, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeClockElement: {
        prototype: HTMLCoreprojectShapeClockElement;
        new (): HTMLCoreprojectShapeClockElement;
    };
    interface HTMLCoreprojectShapeCloudOffElement extends Components.CoreprojectShapeCloudOff, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCloudOffElement: {
        prototype: HTMLCoreprojectShapeCloudOffElement;
        new (): HTMLCoreprojectShapeCloudOffElement;
    };
    interface HTMLCoreprojectShapeCodeElement extends Components.CoreprojectShapeCode, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCodeElement: {
        prototype: HTMLCoreprojectShapeCodeElement;
        new (): HTMLCoreprojectShapeCodeElement;
    };
    interface HTMLCoreprojectShapeCompassElement extends Components.CoreprojectShapeCompass, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCompassElement: {
        prototype: HTMLCoreprojectShapeCompassElement;
        new (): HTMLCoreprojectShapeCompassElement;
    };
    interface HTMLCoreprojectShapeCopyElement extends Components.CoreprojectShapeCopy, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCopyElement: {
        prototype: HTMLCoreprojectShapeCopyElement;
        new (): HTMLCoreprojectShapeCopyElement;
    };
    interface HTMLCoreprojectShapeCornerElement extends Components.CoreprojectShapeCorner, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeCornerElement: {
        prototype: HTMLCoreprojectShapeCornerElement;
        new (): HTMLCoreprojectShapeCornerElement;
    };
    interface HTMLCoreprojectShapeDeleteElement extends Components.CoreprojectShapeDelete, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeDeleteElement: {
        prototype: HTMLCoreprojectShapeDeleteElement;
        new (): HTMLCoreprojectShapeDeleteElement;
    };
    interface HTMLCoreprojectShapeDiceElement extends Components.CoreprojectShapeDice, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeDiceElement: {
        prototype: HTMLCoreprojectShapeDiceElement;
        new (): HTMLCoreprojectShapeDiceElement;
    };
    interface HTMLCoreprojectShapeDownloadElement extends Components.CoreprojectShapeDownload, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeDownloadElement: {
        prototype: HTMLCoreprojectShapeDownloadElement;
        new (): HTMLCoreprojectShapeDownloadElement;
    };
    interface HTMLCoreprojectShapeEditElement extends Components.CoreprojectShapeEdit, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeEditElement: {
        prototype: HTMLCoreprojectShapeEditElement;
        new (): HTMLCoreprojectShapeEditElement;
    };
    interface HTMLCoreprojectShapeExpandElement extends Components.CoreprojectShapeExpand, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeExpandElement: {
        prototype: HTMLCoreprojectShapeExpandElement;
        new (): HTMLCoreprojectShapeExpandElement;
    };
    interface HTMLCoreprojectShapeExternalLinkElement extends Components.CoreprojectShapeExternalLink, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeExternalLinkElement: {
        prototype: HTMLCoreprojectShapeExternalLinkElement;
        new (): HTMLCoreprojectShapeExternalLinkElement;
    };
    interface HTMLCoreprojectShapeEyeElement extends Components.CoreprojectShapeEye, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeEyeElement: {
        prototype: HTMLCoreprojectShapeEyeElement;
        new (): HTMLCoreprojectShapeEyeElement;
    };
    interface HTMLCoreprojectShapeFastForwardElement extends Components.CoreprojectShapeFastForward, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFastForwardElement: {
        prototype: HTMLCoreprojectShapeFastForwardElement;
        new (): HTMLCoreprojectShapeFastForwardElement;
    };
    interface HTMLCoreprojectShapeFileElement extends Components.CoreprojectShapeFile, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFileElement: {
        prototype: HTMLCoreprojectShapeFileElement;
        new (): HTMLCoreprojectShapeFileElement;
    };
    interface HTMLCoreprojectShapeFilterElement extends Components.CoreprojectShapeFilter, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFilterElement: {
        prototype: HTMLCoreprojectShapeFilterElement;
        new (): HTMLCoreprojectShapeFilterElement;
    };
    interface HTMLCoreprojectShapeFlagElement extends Components.CoreprojectShapeFlag, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFlagElement: {
        prototype: HTMLCoreprojectShapeFlagElement;
        new (): HTMLCoreprojectShapeFlagElement;
    };
    interface HTMLCoreprojectShapeFolderElement extends Components.CoreprojectShapeFolder, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFolderElement: {
        prototype: HTMLCoreprojectShapeFolderElement;
        new (): HTMLCoreprojectShapeFolderElement;
    };
    interface HTMLCoreprojectShapeForumElement extends Components.CoreprojectShapeForum, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeForumElement: {
        prototype: HTMLCoreprojectShapeForumElement;
        new (): HTMLCoreprojectShapeForumElement;
    };
    interface HTMLCoreprojectShapeFrownElement extends Components.CoreprojectShapeFrown, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeFrownElement: {
        prototype: HTMLCoreprojectShapeFrownElement;
        new (): HTMLCoreprojectShapeFrownElement;
    };
    interface HTMLCoreprojectShapeGiftElement extends Components.CoreprojectShapeGift, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeGiftElement: {
        prototype: HTMLCoreprojectShapeGiftElement;
        new (): HTMLCoreprojectShapeGiftElement;
    };
    interface HTMLCoreprojectShapeGlobeElement extends Components.CoreprojectShapeGlobe, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeGlobeElement: {
        prototype: HTMLCoreprojectShapeGlobeElement;
        new (): HTMLCoreprojectShapeGlobeElement;
    };
    interface HTMLCoreprojectShapeGridElement extends Components.CoreprojectShapeGrid, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeGridElement: {
        prototype: HTMLCoreprojectShapeGridElement;
        new (): HTMLCoreprojectShapeGridElement;
    };
    interface HTMLCoreprojectShapeHardDriveElement extends Components.CoreprojectShapeHardDrive, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHardDriveElement: {
        prototype: HTMLCoreprojectShapeHardDriveElement;
        new (): HTMLCoreprojectShapeHardDriveElement;
    };
    interface HTMLCoreprojectShapeHashElement extends Components.CoreprojectShapeHash, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHashElement: {
        prototype: HTMLCoreprojectShapeHashElement;
        new (): HTMLCoreprojectShapeHashElement;
    };
    interface HTMLCoreprojectShapeHeadphonesElement extends Components.CoreprojectShapeHeadphones, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHeadphonesElement: {
        prototype: HTMLCoreprojectShapeHeadphonesElement;
        new (): HTMLCoreprojectShapeHeadphonesElement;
    };
    interface HTMLCoreprojectShapeHeartElement extends Components.CoreprojectShapeHeart, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHeartElement: {
        prototype: HTMLCoreprojectShapeHeartElement;
        new (): HTMLCoreprojectShapeHeartElement;
    };
    interface HTMLCoreprojectShapeHelpCircleElement extends Components.CoreprojectShapeHelpCircle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHelpCircleElement: {
        prototype: HTMLCoreprojectShapeHelpCircleElement;
        new (): HTMLCoreprojectShapeHelpCircleElement;
    };
    interface HTMLCoreprojectShapeHomeElement extends Components.CoreprojectShapeHome, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeHomeElement: {
        prototype: HTMLCoreprojectShapeHomeElement;
        new (): HTMLCoreprojectShapeHomeElement;
    };
    interface HTMLCoreprojectShapeInfoElement extends Components.CoreprojectShapeInfo, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeInfoElement: {
        prototype: HTMLCoreprojectShapeInfoElement;
        new (): HTMLCoreprojectShapeInfoElement;
    };
    interface HTMLCoreprojectShapeKeyElement extends Components.CoreprojectShapeKey, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeKeyElement: {
        prototype: HTMLCoreprojectShapeKeyElement;
        new (): HTMLCoreprojectShapeKeyElement;
    };
    interface HTMLCoreprojectShapeLinkElement extends Components.CoreprojectShapeLink, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeLinkElement: {
        prototype: HTMLCoreprojectShapeLinkElement;
        new (): HTMLCoreprojectShapeLinkElement;
    };
    interface HTMLCoreprojectShapeListElement extends Components.CoreprojectShapeList, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeListElement: {
        prototype: HTMLCoreprojectShapeListElement;
        new (): HTMLCoreprojectShapeListElement;
    };
    interface HTMLCoreprojectShapeLockElement extends Components.CoreprojectShapeLock, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeLockElement: {
        prototype: HTMLCoreprojectShapeLockElement;
        new (): HTMLCoreprojectShapeLockElement;
    };
    interface HTMLCoreprojectShapeLogInElement extends Components.CoreprojectShapeLogIn, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeLogInElement: {
        prototype: HTMLCoreprojectShapeLogInElement;
        new (): HTMLCoreprojectShapeLogInElement;
    };
    interface HTMLCoreprojectShapeLogOutElement extends Components.CoreprojectShapeLogOut, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeLogOutElement: {
        prototype: HTMLCoreprojectShapeLogOutElement;
        new (): HTMLCoreprojectShapeLogOutElement;
    };
    interface HTMLCoreprojectShapeLogoElement extends Components.CoreprojectShapeLogo, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeLogoElement: {
        prototype: HTMLCoreprojectShapeLogoElement;
        new (): HTMLCoreprojectShapeLogoElement;
    };
    interface HTMLCoreprojectShapeMailElement extends Components.CoreprojectShapeMail, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMailElement: {
        prototype: HTMLCoreprojectShapeMailElement;
        new (): HTMLCoreprojectShapeMailElement;
    };
    interface HTMLCoreprojectShapeMapPinElement extends Components.CoreprojectShapeMapPin, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMapPinElement: {
        prototype: HTMLCoreprojectShapeMapPinElement;
        new (): HTMLCoreprojectShapeMapPinElement;
    };
    interface HTMLCoreprojectShapeMaximizeElement extends Components.CoreprojectShapeMaximize, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMaximizeElement: {
        prototype: HTMLCoreprojectShapeMaximizeElement;
        new (): HTMLCoreprojectShapeMaximizeElement;
    };
    interface HTMLCoreprojectShapeMehElement extends Components.CoreprojectShapeMeh, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMehElement: {
        prototype: HTMLCoreprojectShapeMehElement;
        new (): HTMLCoreprojectShapeMehElement;
    };
    interface HTMLCoreprojectShapeMessageCircleElement extends Components.CoreprojectShapeMessageCircle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMessageCircleElement: {
        prototype: HTMLCoreprojectShapeMessageCircleElement;
        new (): HTMLCoreprojectShapeMessageCircleElement;
    };
    interface HTMLCoreprojectShapeMinimizeElement extends Components.CoreprojectShapeMinimize, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMinimizeElement: {
        prototype: HTMLCoreprojectShapeMinimizeElement;
        new (): HTMLCoreprojectShapeMinimizeElement;
    };
    interface HTMLCoreprojectShapeMinusElement extends Components.CoreprojectShapeMinus, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMinusElement: {
        prototype: HTMLCoreprojectShapeMinusElement;
        new (): HTMLCoreprojectShapeMinusElement;
    };
    interface HTMLCoreprojectShapeMonitorElement extends Components.CoreprojectShapeMonitor, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMonitorElement: {
        prototype: HTMLCoreprojectShapeMonitorElement;
        new (): HTMLCoreprojectShapeMonitorElement;
    };
    interface HTMLCoreprojectShapeMoonElement extends Components.CoreprojectShapeMoon, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMoonElement: {
        prototype: HTMLCoreprojectShapeMoonElement;
        new (): HTMLCoreprojectShapeMoonElement;
    };
    interface HTMLCoreprojectShapeMoreElement extends Components.CoreprojectShapeMore, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMoreElement: {
        prototype: HTMLCoreprojectShapeMoreElement;
        new (): HTMLCoreprojectShapeMoreElement;
    };
    interface HTMLCoreprojectShapeMousePointerElement extends Components.CoreprojectShapeMousePointer, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMousePointerElement: {
        prototype: HTMLCoreprojectShapeMousePointerElement;
        new (): HTMLCoreprojectShapeMousePointerElement;
    };
    interface HTMLCoreprojectShapeMoveElement extends Components.CoreprojectShapeMove, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeMoveElement: {
        prototype: HTMLCoreprojectShapeMoveElement;
        new (): HTMLCoreprojectShapeMoveElement;
    };
    interface HTMLCoreprojectShapePauseElement extends Components.CoreprojectShapePause, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePauseElement: {
        prototype: HTMLCoreprojectShapePauseElement;
        new (): HTMLCoreprojectShapePauseElement;
    };
    interface HTMLCoreprojectShapePauseCircleElement extends Components.CoreprojectShapePauseCircle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePauseCircleElement: {
        prototype: HTMLCoreprojectShapePauseCircleElement;
        new (): HTMLCoreprojectShapePauseCircleElement;
    };
    interface HTMLCoreprojectShapePlayElement extends Components.CoreprojectShapePlay, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePlayElement: {
        prototype: HTMLCoreprojectShapePlayElement;
        new (): HTMLCoreprojectShapePlayElement;
    };
    interface HTMLCoreprojectShapePlayCircleElement extends Components.CoreprojectShapePlayCircle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePlayCircleElement: {
        prototype: HTMLCoreprojectShapePlayCircleElement;
        new (): HTMLCoreprojectShapePlayCircleElement;
    };
    interface HTMLCoreprojectShapePlusElement extends Components.CoreprojectShapePlus, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePlusElement: {
        prototype: HTMLCoreprojectShapePlusElement;
        new (): HTMLCoreprojectShapePlusElement;
    };
    interface HTMLCoreprojectShapePreferencesElement extends Components.CoreprojectShapePreferences, HTMLStencilElement {
    }
    var HTMLCoreprojectShapePreferencesElement: {
        prototype: HTMLCoreprojectShapePreferencesElement;
        new (): HTMLCoreprojectShapePreferencesElement;
    };
    interface HTMLCoreprojectShapeRefreshElement extends Components.CoreprojectShapeRefresh, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeRefreshElement: {
        prototype: HTMLCoreprojectShapeRefreshElement;
        new (): HTMLCoreprojectShapeRefreshElement;
    };
    interface HTMLCoreprojectShapeRepeatElement extends Components.CoreprojectShapeRepeat, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeRepeatElement: {
        prototype: HTMLCoreprojectShapeRepeatElement;
        new (): HTMLCoreprojectShapeRepeatElement;
    };
    interface HTMLCoreprojectShapeRotateElement extends Components.CoreprojectShapeRotate, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeRotateElement: {
        prototype: HTMLCoreprojectShapeRotateElement;
        new (): HTMLCoreprojectShapeRotateElement;
    };
    interface HTMLCoreprojectShapeSaveElement extends Components.CoreprojectShapeSave, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSaveElement: {
        prototype: HTMLCoreprojectShapeSaveElement;
        new (): HTMLCoreprojectShapeSaveElement;
    };
    interface HTMLCoreprojectShapeSearchElement extends Components.CoreprojectShapeSearch, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSearchElement: {
        prototype: HTMLCoreprojectShapeSearchElement;
        new (): HTMLCoreprojectShapeSearchElement;
    };
    interface HTMLCoreprojectShapeSettingsElement extends Components.CoreprojectShapeSettings, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSettingsElement: {
        prototype: HTMLCoreprojectShapeSettingsElement;
        new (): HTMLCoreprojectShapeSettingsElement;
    };
    interface HTMLCoreprojectShapeShareElement extends Components.CoreprojectShapeShare, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeShareElement: {
        prototype: HTMLCoreprojectShapeShareElement;
        new (): HTMLCoreprojectShapeShareElement;
    };
    interface HTMLCoreprojectShapeShieldElement extends Components.CoreprojectShapeShield, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeShieldElement: {
        prototype: HTMLCoreprojectShapeShieldElement;
        new (): HTMLCoreprojectShapeShieldElement;
    };
    interface HTMLCoreprojectShapeShoppingCartElement extends Components.CoreprojectShapeShoppingCart, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeShoppingCartElement: {
        prototype: HTMLCoreprojectShapeShoppingCartElement;
        new (): HTMLCoreprojectShapeShoppingCartElement;
    };
    interface HTMLCoreprojectShapeShrinkElement extends Components.CoreprojectShapeShrink, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeShrinkElement: {
        prototype: HTMLCoreprojectShapeShrinkElement;
        new (): HTMLCoreprojectShapeShrinkElement;
    };
    interface HTMLCoreprojectShapeSmartphoneElement extends Components.CoreprojectShapeSmartphone, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSmartphoneElement: {
        prototype: HTMLCoreprojectShapeSmartphoneElement;
        new (): HTMLCoreprojectShapeSmartphoneElement;
    };
    interface HTMLCoreprojectShapeSmileElement extends Components.CoreprojectShapeSmile, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSmileElement: {
        prototype: HTMLCoreprojectShapeSmileElement;
        new (): HTMLCoreprojectShapeSmileElement;
    };
    interface HTMLCoreprojectShapeSpeakerElement extends Components.CoreprojectShapeSpeaker, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSpeakerElement: {
        prototype: HTMLCoreprojectShapeSpeakerElement;
        new (): HTMLCoreprojectShapeSpeakerElement;
    };
    interface HTMLCoreprojectShapeStarElement extends Components.CoreprojectShapeStar, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeStarElement: {
        prototype: HTMLCoreprojectShapeStarElement;
        new (): HTMLCoreprojectShapeStarElement;
    };
    interface HTMLCoreprojectShapeSunElement extends Components.CoreprojectShapeSun, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeSunElement: {
        prototype: HTMLCoreprojectShapeSunElement;
        new (): HTMLCoreprojectShapeSunElement;
    };
    interface HTMLCoreprojectShapeTagElement extends Components.CoreprojectShapeTag, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTagElement: {
        prototype: HTMLCoreprojectShapeTagElement;
        new (): HTMLCoreprojectShapeTagElement;
    };
    interface HTMLCoreprojectShapeTerminalElement extends Components.CoreprojectShapeTerminal, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTerminalElement: {
        prototype: HTMLCoreprojectShapeTerminalElement;
        new (): HTMLCoreprojectShapeTerminalElement;
    };
    interface HTMLCoreprojectShapeThumbsElement extends Components.CoreprojectShapeThumbs, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeThumbsElement: {
        prototype: HTMLCoreprojectShapeThumbsElement;
        new (): HTMLCoreprojectShapeThumbsElement;
    };
    interface HTMLCoreprojectShapeToggleElement extends Components.CoreprojectShapeToggle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeToggleElement: {
        prototype: HTMLCoreprojectShapeToggleElement;
        new (): HTMLCoreprojectShapeToggleElement;
    };
    interface HTMLCoreprojectShapeToolElement extends Components.CoreprojectShapeTool, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeToolElement: {
        prototype: HTMLCoreprojectShapeToolElement;
        new (): HTMLCoreprojectShapeToolElement;
    };
    interface HTMLCoreprojectShapeTrashElement extends Components.CoreprojectShapeTrash, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTrashElement: {
        prototype: HTMLCoreprojectShapeTrashElement;
        new (): HTMLCoreprojectShapeTrashElement;
    };
    interface HTMLCoreprojectShapeTrendingElement extends Components.CoreprojectShapeTrending, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTrendingElement: {
        prototype: HTMLCoreprojectShapeTrendingElement;
        new (): HTMLCoreprojectShapeTrendingElement;
    };
    interface HTMLCoreprojectShapeTriangleElement extends Components.CoreprojectShapeTriangle, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTriangleElement: {
        prototype: HTMLCoreprojectShapeTriangleElement;
        new (): HTMLCoreprojectShapeTriangleElement;
    };
    interface HTMLCoreprojectShapeTwitterElement extends Components.CoreprojectShapeTwitter, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTwitterElement: {
        prototype: HTMLCoreprojectShapeTwitterElement;
        new (): HTMLCoreprojectShapeTwitterElement;
    };
    interface HTMLCoreprojectShapeTypeElement extends Components.CoreprojectShapeType, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeTypeElement: {
        prototype: HTMLCoreprojectShapeTypeElement;
        new (): HTMLCoreprojectShapeTypeElement;
    };
    interface HTMLCoreprojectShapeUnderlineElement extends Components.CoreprojectShapeUnderline, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeUnderlineElement: {
        prototype: HTMLCoreprojectShapeUnderlineElement;
        new (): HTMLCoreprojectShapeUnderlineElement;
    };
    interface HTMLCoreprojectShapeUnlockElement extends Components.CoreprojectShapeUnlock, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeUnlockElement: {
        prototype: HTMLCoreprojectShapeUnlockElement;
        new (): HTMLCoreprojectShapeUnlockElement;
    };
    interface HTMLCoreprojectShapeUploadElement extends Components.CoreprojectShapeUpload, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeUploadElement: {
        prototype: HTMLCoreprojectShapeUploadElement;
        new (): HTMLCoreprojectShapeUploadElement;
    };
    interface HTMLCoreprojectShapeUserElement extends Components.CoreprojectShapeUser, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeUserElement: {
        prototype: HTMLCoreprojectShapeUserElement;
        new (): HTMLCoreprojectShapeUserElement;
    };
    interface HTMLCoreprojectShapeUsersElement extends Components.CoreprojectShapeUsers, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeUsersElement: {
        prototype: HTMLCoreprojectShapeUsersElement;
        new (): HTMLCoreprojectShapeUsersElement;
    };
    interface HTMLCoreprojectShapeVolumeElement extends Components.CoreprojectShapeVolume, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeVolumeElement: {
        prototype: HTMLCoreprojectShapeVolumeElement;
        new (): HTMLCoreprojectShapeVolumeElement;
    };
    interface HTMLCoreprojectShapeXElement extends Components.CoreprojectShapeX, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeXElement: {
        prototype: HTMLCoreprojectShapeXElement;
        new (): HTMLCoreprojectShapeXElement;
    };
    interface HTMLCoreprojectShapeZapOffElement extends Components.CoreprojectShapeZapOff, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeZapOffElement: {
        prototype: HTMLCoreprojectShapeZapOffElement;
        new (): HTMLCoreprojectShapeZapOffElement;
    };
    interface HTMLCoreprojectShapeZoomElement extends Components.CoreprojectShapeZoom, HTMLStencilElement {
    }
    var HTMLCoreprojectShapeZoomElement: {
        prototype: HTMLCoreprojectShapeZoomElement;
        new (): HTMLCoreprojectShapeZoomElement;
    };
    interface HTMLElementTagNameMap {
        "coreproject-logo-discord": HTMLCoreprojectLogoDiscordElement;
        "coreproject-logo-figma": HTMLCoreprojectLogoFigmaElement;
        "coreproject-logo-github": HTMLCoreprojectLogoGithubElement;
        "coreproject-logo-reddit": HTMLCoreprojectLogoRedditElement;
        "coreproject-shape-airplay": HTMLCoreprojectShapeAirplayElement;
        "coreproject-shape-alert-triangle": HTMLCoreprojectShapeAlertTriangleElement;
        "coreproject-shape-align": HTMLCoreprojectShapeAlignElement;
        "coreproject-shape-arrow": HTMLCoreprojectShapeArrowElement;
        "coreproject-shape-at-sign": HTMLCoreprojectShapeAtSignElement;
        "coreproject-shape-award": HTMLCoreprojectShapeAwardElement;
        "coreproject-shape-bar-chart": HTMLCoreprojectShapeBarChartElement;
        "coreproject-shape-bell": HTMLCoreprojectShapeBellElement;
        "coreproject-shape-book": HTMLCoreprojectShapeBookElement;
        "coreproject-shape-box": HTMLCoreprojectShapeBoxElement;
        "coreproject-shape-calendar": HTMLCoreprojectShapeCalendarElement;
        "coreproject-shape-cast": HTMLCoreprojectShapeCastElement;
        "coreproject-shape-check": HTMLCoreprojectShapeCheckElement;
        "coreproject-shape-chevron": HTMLCoreprojectShapeChevronElement;
        "coreproject-shape-chevrons": HTMLCoreprojectShapeChevronsElement;
        "coreproject-shape-circle": HTMLCoreprojectShapeCircleElement;
        "coreproject-shape-clipboard": HTMLCoreprojectShapeClipboardElement;
        "coreproject-shape-clock": HTMLCoreprojectShapeClockElement;
        "coreproject-shape-cloud-off": HTMLCoreprojectShapeCloudOffElement;
        "coreproject-shape-code": HTMLCoreprojectShapeCodeElement;
        "coreproject-shape-compass": HTMLCoreprojectShapeCompassElement;
        "coreproject-shape-copy": HTMLCoreprojectShapeCopyElement;
        "coreproject-shape-corner": HTMLCoreprojectShapeCornerElement;
        "coreproject-shape-delete": HTMLCoreprojectShapeDeleteElement;
        "coreproject-shape-dice": HTMLCoreprojectShapeDiceElement;
        "coreproject-shape-download": HTMLCoreprojectShapeDownloadElement;
        "coreproject-shape-edit": HTMLCoreprojectShapeEditElement;
        "coreproject-shape-expand": HTMLCoreprojectShapeExpandElement;
        "coreproject-shape-external-link": HTMLCoreprojectShapeExternalLinkElement;
        "coreproject-shape-eye": HTMLCoreprojectShapeEyeElement;
        "coreproject-shape-fast-forward": HTMLCoreprojectShapeFastForwardElement;
        "coreproject-shape-file": HTMLCoreprojectShapeFileElement;
        "coreproject-shape-filter": HTMLCoreprojectShapeFilterElement;
        "coreproject-shape-flag": HTMLCoreprojectShapeFlagElement;
        "coreproject-shape-folder": HTMLCoreprojectShapeFolderElement;
        "coreproject-shape-forum": HTMLCoreprojectShapeForumElement;
        "coreproject-shape-frown": HTMLCoreprojectShapeFrownElement;
        "coreproject-shape-gift": HTMLCoreprojectShapeGiftElement;
        "coreproject-shape-globe": HTMLCoreprojectShapeGlobeElement;
        "coreproject-shape-grid": HTMLCoreprojectShapeGridElement;
        "coreproject-shape-hard-drive": HTMLCoreprojectShapeHardDriveElement;
        "coreproject-shape-hash": HTMLCoreprojectShapeHashElement;
        "coreproject-shape-headphones": HTMLCoreprojectShapeHeadphonesElement;
        "coreproject-shape-heart": HTMLCoreprojectShapeHeartElement;
        "coreproject-shape-help-circle": HTMLCoreprojectShapeHelpCircleElement;
        "coreproject-shape-home": HTMLCoreprojectShapeHomeElement;
        "coreproject-shape-info": HTMLCoreprojectShapeInfoElement;
        "coreproject-shape-key": HTMLCoreprojectShapeKeyElement;
        "coreproject-shape-link": HTMLCoreprojectShapeLinkElement;
        "coreproject-shape-list": HTMLCoreprojectShapeListElement;
        "coreproject-shape-lock": HTMLCoreprojectShapeLockElement;
        "coreproject-shape-log-in": HTMLCoreprojectShapeLogInElement;
        "coreproject-shape-log-out": HTMLCoreprojectShapeLogOutElement;
        "coreproject-shape-logo": HTMLCoreprojectShapeLogoElement;
        "coreproject-shape-mail": HTMLCoreprojectShapeMailElement;
        "coreproject-shape-map-pin": HTMLCoreprojectShapeMapPinElement;
        "coreproject-shape-maximize": HTMLCoreprojectShapeMaximizeElement;
        "coreproject-shape-meh": HTMLCoreprojectShapeMehElement;
        "coreproject-shape-message-circle": HTMLCoreprojectShapeMessageCircleElement;
        "coreproject-shape-minimize": HTMLCoreprojectShapeMinimizeElement;
        "coreproject-shape-minus": HTMLCoreprojectShapeMinusElement;
        "coreproject-shape-monitor": HTMLCoreprojectShapeMonitorElement;
        "coreproject-shape-moon": HTMLCoreprojectShapeMoonElement;
        "coreproject-shape-more": HTMLCoreprojectShapeMoreElement;
        "coreproject-shape-mouse-pointer": HTMLCoreprojectShapeMousePointerElement;
        "coreproject-shape-move": HTMLCoreprojectShapeMoveElement;
        "coreproject-shape-pause": HTMLCoreprojectShapePauseElement;
        "coreproject-shape-pause-circle": HTMLCoreprojectShapePauseCircleElement;
        "coreproject-shape-play": HTMLCoreprojectShapePlayElement;
        "coreproject-shape-play-circle": HTMLCoreprojectShapePlayCircleElement;
        "coreproject-shape-plus": HTMLCoreprojectShapePlusElement;
        "coreproject-shape-preferences": HTMLCoreprojectShapePreferencesElement;
        "coreproject-shape-refresh": HTMLCoreprojectShapeRefreshElement;
        "coreproject-shape-repeat": HTMLCoreprojectShapeRepeatElement;
        "coreproject-shape-rotate": HTMLCoreprojectShapeRotateElement;
        "coreproject-shape-save": HTMLCoreprojectShapeSaveElement;
        "coreproject-shape-search": HTMLCoreprojectShapeSearchElement;
        "coreproject-shape-settings": HTMLCoreprojectShapeSettingsElement;
        "coreproject-shape-share": HTMLCoreprojectShapeShareElement;
        "coreproject-shape-shield": HTMLCoreprojectShapeShieldElement;
        "coreproject-shape-shopping-cart": HTMLCoreprojectShapeShoppingCartElement;
        "coreproject-shape-shrink": HTMLCoreprojectShapeShrinkElement;
        "coreproject-shape-smartphone": HTMLCoreprojectShapeSmartphoneElement;
        "coreproject-shape-smile": HTMLCoreprojectShapeSmileElement;
        "coreproject-shape-speaker": HTMLCoreprojectShapeSpeakerElement;
        "coreproject-shape-star": HTMLCoreprojectShapeStarElement;
        "coreproject-shape-sun": HTMLCoreprojectShapeSunElement;
        "coreproject-shape-tag": HTMLCoreprojectShapeTagElement;
        "coreproject-shape-terminal": HTMLCoreprojectShapeTerminalElement;
        "coreproject-shape-thumbs": HTMLCoreprojectShapeThumbsElement;
        "coreproject-shape-toggle": HTMLCoreprojectShapeToggleElement;
        "coreproject-shape-tool": HTMLCoreprojectShapeToolElement;
        "coreproject-shape-trash": HTMLCoreprojectShapeTrashElement;
        "coreproject-shape-trending": HTMLCoreprojectShapeTrendingElement;
        "coreproject-shape-triangle": HTMLCoreprojectShapeTriangleElement;
        "coreproject-shape-twitter": HTMLCoreprojectShapeTwitterElement;
        "coreproject-shape-type": HTMLCoreprojectShapeTypeElement;
        "coreproject-shape-underline": HTMLCoreprojectShapeUnderlineElement;
        "coreproject-shape-unlock": HTMLCoreprojectShapeUnlockElement;
        "coreproject-shape-upload": HTMLCoreprojectShapeUploadElement;
        "coreproject-shape-user": HTMLCoreprojectShapeUserElement;
        "coreproject-shape-users": HTMLCoreprojectShapeUsersElement;
        "coreproject-shape-volume": HTMLCoreprojectShapeVolumeElement;
        "coreproject-shape-x": HTMLCoreprojectShapeXElement;
        "coreproject-shape-zap-off": HTMLCoreprojectShapeZapOffElement;
        "coreproject-shape-zoom": HTMLCoreprojectShapeZoomElement;
    }
}
declare namespace LocalJSX {
    interface CoreprojectLogoDiscord {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectLogoFigma {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectLogoGithub {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectLogoReddit {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeAirplay {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeAlertTriangle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeAlign {
        "_style"?: string;
        "height"?: string | number;
        "variant": "center" | "justify" | "left" | "right";
        "width"?: string | number;
    }
    interface CoreprojectShapeArrow {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeAtSign {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeAward {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeBarChart {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeBell {
        "_style"?: string;
        "height"?: string | number;
        "variant": "on" | "off";
        "width"?: string | number;
    }
    interface CoreprojectShapeBook {
        "_style"?: string;
        "height"?: string | number;
        "variant": "open" | "close";
        "width"?: string | number;
    }
    interface CoreprojectShapeBox {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCalendar {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCast {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCheck {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeChevron {
        "_style"?: string;
        "height"?: string | number;
        "variant": "up" | "right" | "down" | "left";
        "width"?: string | number;
    }
    interface CoreprojectShapeChevrons {
        "_style"?: string;
        "height"?: string | number;
        "variant": "up" | "right" | "down" | "left";
        "width"?: string | number;
    }
    interface CoreprojectShapeCircle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeClipboard {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeClock {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCloudOff {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCode {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCompass {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCopy {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeCorner {
        "_style"?: string;
        "height"?: string | number;
        "variant": "down-right" | "down-left" | "left-down" | "left-up" | "up-left" | "up-right" | "right-up" | "right-down";
        "width"?: string | number;
    }
    interface CoreprojectShapeDelete {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeDice {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeDownload {
        "_style"?: string;
        "height"?: string | number;
        "variant": "arrow" | "cloud";
        "width"?: string | number;
    }
    interface CoreprojectShapeEdit {
        "_style"?: string;
        "height"?: string | number;
        "variant": "box" | "pencil" | "line-with-pencil";
        "width"?: string | number;
    }
    interface CoreprojectShapeExpand {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeExternalLink {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeEye {
        "_style"?: string;
        "height"?: string | number;
        "variant": "open" | "close";
        "width"?: string | number;
    }
    interface CoreprojectShapeFastForward {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeFile {
        "_style"?: string;
        "height"?: string | number;
        "variant": "normal" | "minus" | "plus" | "text";
        "width"?: string | number;
    }
    interface CoreprojectShapeFilter {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeFlag {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeFolder {
        "_style"?: string;
        "height"?: string | number;
        "variant": "normal" | "minus" | "plus";
        "width"?: string | number;
    }
    interface CoreprojectShapeForum {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeFrown {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeGift {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeGlobe {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeGrid {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHardDrive {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHash {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHeadphones {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHeart {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHelpCircle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeHome {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeInfo {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeKey {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeLink {
        "_style"?: string;
        "height"?: string | number;
        "variant": "tilted" | "horizontal";
        "width"?: string | number;
    }
    interface CoreprojectShapeList {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeLock {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeLogIn {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeLogOut {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeLogo {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMail {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMapPin {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMaximize {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMeh {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMessageCircle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMinimize {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMinus {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMonitor {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMoon {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMore {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMousePointer {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeMove {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapePause {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapePauseCircle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapePlay {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapePlayCircle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapePlus {
        "_style"?: string;
        "height"?: string | number;
        "variant": "no-border" | "circle" | "square";
        "width"?: string | number;
    }
    interface CoreprojectShapePreferences {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeRefresh {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeRepeat {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeRotate {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSave {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSearch {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSettings {
        "_style"?: string;
        "height"?: string | number;
        "variant": "outline" | "filled";
        "width"?: string | number;
    }
    interface CoreprojectShapeShare {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeShield {
        "_style"?: string;
        "height"?: string | number;
        "variant": "on" | "off";
        "width"?: string | number;
    }
    interface CoreprojectShapeShoppingCart {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeShrink {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSmartphone {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSmile {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSpeaker {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeStar {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeSun {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeTag {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeTerminal {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeThumbs {
        "_style"?: string;
        "height"?: string | number;
        "variant": "up" | "down";
        "width"?: string | number;
    }
    interface CoreprojectShapeToggle {
        "_style"?: string;
        "height"?: string | number;
        "variant": "off" | "on";
        "width"?: string | number;
    }
    interface CoreprojectShapeTool {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeTrash {
        "_style"?: string;
        "height"?: string | number;
        "variant": "with-lines" | "without-lines";
        "width"?: string | number;
    }
    interface CoreprojectShapeTrending {
        "_style"?: string;
        "height"?: string | number;
        "variant": "up" | "down";
        "width"?: string | number;
    }
    interface CoreprojectShapeTriangle {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeTwitter {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeType {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeUnderline {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeUnlock {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeUpload {
        "_style"?: string;
        "height"?: string | number;
        "variant": "arrow" | "cloud";
        "width"?: string | number;
    }
    interface CoreprojectShapeUser {
        "_style"?: string;
        "height"?: string | number;
        "variant": "normal" | "check" | "minus" | "plus" | "x";
        "width"?: string | number;
    }
    interface CoreprojectShapeUsers {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeVolume {
        "_style"?: string;
        "height"?: string | number;
        "variant": "off" | "half" | "full" | "mute";
        "width"?: string | number;
    }
    interface CoreprojectShapeX {
        "_style"?: string;
        "height"?: string | number;
        "variant": "no-border" | "circle" | "octagon" | "square";
        "width"?: string | number;
    }
    interface CoreprojectShapeZapOff {
        "_style"?: string;
        "height"?: string | number;
        "width"?: string | number;
    }
    interface CoreprojectShapeZoom {
        "_style"?: string;
        "height"?: string | number;
        "variant": "in" | "out";
        "width"?: string | number;
    }
    interface IntrinsicElements {
        "coreproject-logo-discord": CoreprojectLogoDiscord;
        "coreproject-logo-figma": CoreprojectLogoFigma;
        "coreproject-logo-github": CoreprojectLogoGithub;
        "coreproject-logo-reddit": CoreprojectLogoReddit;
        "coreproject-shape-airplay": CoreprojectShapeAirplay;
        "coreproject-shape-alert-triangle": CoreprojectShapeAlertTriangle;
        "coreproject-shape-align": CoreprojectShapeAlign;
        "coreproject-shape-arrow": CoreprojectShapeArrow;
        "coreproject-shape-at-sign": CoreprojectShapeAtSign;
        "coreproject-shape-award": CoreprojectShapeAward;
        "coreproject-shape-bar-chart": CoreprojectShapeBarChart;
        "coreproject-shape-bell": CoreprojectShapeBell;
        "coreproject-shape-book": CoreprojectShapeBook;
        "coreproject-shape-box": CoreprojectShapeBox;
        "coreproject-shape-calendar": CoreprojectShapeCalendar;
        "coreproject-shape-cast": CoreprojectShapeCast;
        "coreproject-shape-check": CoreprojectShapeCheck;
        "coreproject-shape-chevron": CoreprojectShapeChevron;
        "coreproject-shape-chevrons": CoreprojectShapeChevrons;
        "coreproject-shape-circle": CoreprojectShapeCircle;
        "coreproject-shape-clipboard": CoreprojectShapeClipboard;
        "coreproject-shape-clock": CoreprojectShapeClock;
        "coreproject-shape-cloud-off": CoreprojectShapeCloudOff;
        "coreproject-shape-code": CoreprojectShapeCode;
        "coreproject-shape-compass": CoreprojectShapeCompass;
        "coreproject-shape-copy": CoreprojectShapeCopy;
        "coreproject-shape-corner": CoreprojectShapeCorner;
        "coreproject-shape-delete": CoreprojectShapeDelete;
        "coreproject-shape-dice": CoreprojectShapeDice;
        "coreproject-shape-download": CoreprojectShapeDownload;
        "coreproject-shape-edit": CoreprojectShapeEdit;
        "coreproject-shape-expand": CoreprojectShapeExpand;
        "coreproject-shape-external-link": CoreprojectShapeExternalLink;
        "coreproject-shape-eye": CoreprojectShapeEye;
        "coreproject-shape-fast-forward": CoreprojectShapeFastForward;
        "coreproject-shape-file": CoreprojectShapeFile;
        "coreproject-shape-filter": CoreprojectShapeFilter;
        "coreproject-shape-flag": CoreprojectShapeFlag;
        "coreproject-shape-folder": CoreprojectShapeFolder;
        "coreproject-shape-forum": CoreprojectShapeForum;
        "coreproject-shape-frown": CoreprojectShapeFrown;
        "coreproject-shape-gift": CoreprojectShapeGift;
        "coreproject-shape-globe": CoreprojectShapeGlobe;
        "coreproject-shape-grid": CoreprojectShapeGrid;
        "coreproject-shape-hard-drive": CoreprojectShapeHardDrive;
        "coreproject-shape-hash": CoreprojectShapeHash;
        "coreproject-shape-headphones": CoreprojectShapeHeadphones;
        "coreproject-shape-heart": CoreprojectShapeHeart;
        "coreproject-shape-help-circle": CoreprojectShapeHelpCircle;
        "coreproject-shape-home": CoreprojectShapeHome;
        "coreproject-shape-info": CoreprojectShapeInfo;
        "coreproject-shape-key": CoreprojectShapeKey;
        "coreproject-shape-link": CoreprojectShapeLink;
        "coreproject-shape-list": CoreprojectShapeList;
        "coreproject-shape-lock": CoreprojectShapeLock;
        "coreproject-shape-log-in": CoreprojectShapeLogIn;
        "coreproject-shape-log-out": CoreprojectShapeLogOut;
        "coreproject-shape-logo": CoreprojectShapeLogo;
        "coreproject-shape-mail": CoreprojectShapeMail;
        "coreproject-shape-map-pin": CoreprojectShapeMapPin;
        "coreproject-shape-maximize": CoreprojectShapeMaximize;
        "coreproject-shape-meh": CoreprojectShapeMeh;
        "coreproject-shape-message-circle": CoreprojectShapeMessageCircle;
        "coreproject-shape-minimize": CoreprojectShapeMinimize;
        "coreproject-shape-minus": CoreprojectShapeMinus;
        "coreproject-shape-monitor": CoreprojectShapeMonitor;
        "coreproject-shape-moon": CoreprojectShapeMoon;
        "coreproject-shape-more": CoreprojectShapeMore;
        "coreproject-shape-mouse-pointer": CoreprojectShapeMousePointer;
        "coreproject-shape-move": CoreprojectShapeMove;
        "coreproject-shape-pause": CoreprojectShapePause;
        "coreproject-shape-pause-circle": CoreprojectShapePauseCircle;
        "coreproject-shape-play": CoreprojectShapePlay;
        "coreproject-shape-play-circle": CoreprojectShapePlayCircle;
        "coreproject-shape-plus": CoreprojectShapePlus;
        "coreproject-shape-preferences": CoreprojectShapePreferences;
        "coreproject-shape-refresh": CoreprojectShapeRefresh;
        "coreproject-shape-repeat": CoreprojectShapeRepeat;
        "coreproject-shape-rotate": CoreprojectShapeRotate;
        "coreproject-shape-save": CoreprojectShapeSave;
        "coreproject-shape-search": CoreprojectShapeSearch;
        "coreproject-shape-settings": CoreprojectShapeSettings;
        "coreproject-shape-share": CoreprojectShapeShare;
        "coreproject-shape-shield": CoreprojectShapeShield;
        "coreproject-shape-shopping-cart": CoreprojectShapeShoppingCart;
        "coreproject-shape-shrink": CoreprojectShapeShrink;
        "coreproject-shape-smartphone": CoreprojectShapeSmartphone;
        "coreproject-shape-smile": CoreprojectShapeSmile;
        "coreproject-shape-speaker": CoreprojectShapeSpeaker;
        "coreproject-shape-star": CoreprojectShapeStar;
        "coreproject-shape-sun": CoreprojectShapeSun;
        "coreproject-shape-tag": CoreprojectShapeTag;
        "coreproject-shape-terminal": CoreprojectShapeTerminal;
        "coreproject-shape-thumbs": CoreprojectShapeThumbs;
        "coreproject-shape-toggle": CoreprojectShapeToggle;
        "coreproject-shape-tool": CoreprojectShapeTool;
        "coreproject-shape-trash": CoreprojectShapeTrash;
        "coreproject-shape-trending": CoreprojectShapeTrending;
        "coreproject-shape-triangle": CoreprojectShapeTriangle;
        "coreproject-shape-twitter": CoreprojectShapeTwitter;
        "coreproject-shape-type": CoreprojectShapeType;
        "coreproject-shape-underline": CoreprojectShapeUnderline;
        "coreproject-shape-unlock": CoreprojectShapeUnlock;
        "coreproject-shape-upload": CoreprojectShapeUpload;
        "coreproject-shape-user": CoreprojectShapeUser;
        "coreproject-shape-users": CoreprojectShapeUsers;
        "coreproject-shape-volume": CoreprojectShapeVolume;
        "coreproject-shape-x": CoreprojectShapeX;
        "coreproject-shape-zap-off": CoreprojectShapeZapOff;
        "coreproject-shape-zoom": CoreprojectShapeZoom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "coreproject-logo-discord": LocalJSX.CoreprojectLogoDiscord & JSXBase.HTMLAttributes<HTMLCoreprojectLogoDiscordElement>;
            "coreproject-logo-figma": LocalJSX.CoreprojectLogoFigma & JSXBase.HTMLAttributes<HTMLCoreprojectLogoFigmaElement>;
            "coreproject-logo-github": LocalJSX.CoreprojectLogoGithub & JSXBase.HTMLAttributes<HTMLCoreprojectLogoGithubElement>;
            "coreproject-logo-reddit": LocalJSX.CoreprojectLogoReddit & JSXBase.HTMLAttributes<HTMLCoreprojectLogoRedditElement>;
            "coreproject-shape-airplay": LocalJSX.CoreprojectShapeAirplay & JSXBase.HTMLAttributes<HTMLCoreprojectShapeAirplayElement>;
            "coreproject-shape-alert-triangle": LocalJSX.CoreprojectShapeAlertTriangle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeAlertTriangleElement>;
            "coreproject-shape-align": LocalJSX.CoreprojectShapeAlign & JSXBase.HTMLAttributes<HTMLCoreprojectShapeAlignElement>;
            "coreproject-shape-arrow": LocalJSX.CoreprojectShapeArrow & JSXBase.HTMLAttributes<HTMLCoreprojectShapeArrowElement>;
            "coreproject-shape-at-sign": LocalJSX.CoreprojectShapeAtSign & JSXBase.HTMLAttributes<HTMLCoreprojectShapeAtSignElement>;
            "coreproject-shape-award": LocalJSX.CoreprojectShapeAward & JSXBase.HTMLAttributes<HTMLCoreprojectShapeAwardElement>;
            "coreproject-shape-bar-chart": LocalJSX.CoreprojectShapeBarChart & JSXBase.HTMLAttributes<HTMLCoreprojectShapeBarChartElement>;
            "coreproject-shape-bell": LocalJSX.CoreprojectShapeBell & JSXBase.HTMLAttributes<HTMLCoreprojectShapeBellElement>;
            "coreproject-shape-book": LocalJSX.CoreprojectShapeBook & JSXBase.HTMLAttributes<HTMLCoreprojectShapeBookElement>;
            "coreproject-shape-box": LocalJSX.CoreprojectShapeBox & JSXBase.HTMLAttributes<HTMLCoreprojectShapeBoxElement>;
            "coreproject-shape-calendar": LocalJSX.CoreprojectShapeCalendar & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCalendarElement>;
            "coreproject-shape-cast": LocalJSX.CoreprojectShapeCast & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCastElement>;
            "coreproject-shape-check": LocalJSX.CoreprojectShapeCheck & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCheckElement>;
            "coreproject-shape-chevron": LocalJSX.CoreprojectShapeChevron & JSXBase.HTMLAttributes<HTMLCoreprojectShapeChevronElement>;
            "coreproject-shape-chevrons": LocalJSX.CoreprojectShapeChevrons & JSXBase.HTMLAttributes<HTMLCoreprojectShapeChevronsElement>;
            "coreproject-shape-circle": LocalJSX.CoreprojectShapeCircle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCircleElement>;
            "coreproject-shape-clipboard": LocalJSX.CoreprojectShapeClipboard & JSXBase.HTMLAttributes<HTMLCoreprojectShapeClipboardElement>;
            "coreproject-shape-clock": LocalJSX.CoreprojectShapeClock & JSXBase.HTMLAttributes<HTMLCoreprojectShapeClockElement>;
            "coreproject-shape-cloud-off": LocalJSX.CoreprojectShapeCloudOff & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCloudOffElement>;
            "coreproject-shape-code": LocalJSX.CoreprojectShapeCode & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCodeElement>;
            "coreproject-shape-compass": LocalJSX.CoreprojectShapeCompass & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCompassElement>;
            "coreproject-shape-copy": LocalJSX.CoreprojectShapeCopy & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCopyElement>;
            "coreproject-shape-corner": LocalJSX.CoreprojectShapeCorner & JSXBase.HTMLAttributes<HTMLCoreprojectShapeCornerElement>;
            "coreproject-shape-delete": LocalJSX.CoreprojectShapeDelete & JSXBase.HTMLAttributes<HTMLCoreprojectShapeDeleteElement>;
            "coreproject-shape-dice": LocalJSX.CoreprojectShapeDice & JSXBase.HTMLAttributes<HTMLCoreprojectShapeDiceElement>;
            "coreproject-shape-download": LocalJSX.CoreprojectShapeDownload & JSXBase.HTMLAttributes<HTMLCoreprojectShapeDownloadElement>;
            "coreproject-shape-edit": LocalJSX.CoreprojectShapeEdit & JSXBase.HTMLAttributes<HTMLCoreprojectShapeEditElement>;
            "coreproject-shape-expand": LocalJSX.CoreprojectShapeExpand & JSXBase.HTMLAttributes<HTMLCoreprojectShapeExpandElement>;
            "coreproject-shape-external-link": LocalJSX.CoreprojectShapeExternalLink & JSXBase.HTMLAttributes<HTMLCoreprojectShapeExternalLinkElement>;
            "coreproject-shape-eye": LocalJSX.CoreprojectShapeEye & JSXBase.HTMLAttributes<HTMLCoreprojectShapeEyeElement>;
            "coreproject-shape-fast-forward": LocalJSX.CoreprojectShapeFastForward & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFastForwardElement>;
            "coreproject-shape-file": LocalJSX.CoreprojectShapeFile & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFileElement>;
            "coreproject-shape-filter": LocalJSX.CoreprojectShapeFilter & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFilterElement>;
            "coreproject-shape-flag": LocalJSX.CoreprojectShapeFlag & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFlagElement>;
            "coreproject-shape-folder": LocalJSX.CoreprojectShapeFolder & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFolderElement>;
            "coreproject-shape-forum": LocalJSX.CoreprojectShapeForum & JSXBase.HTMLAttributes<HTMLCoreprojectShapeForumElement>;
            "coreproject-shape-frown": LocalJSX.CoreprojectShapeFrown & JSXBase.HTMLAttributes<HTMLCoreprojectShapeFrownElement>;
            "coreproject-shape-gift": LocalJSX.CoreprojectShapeGift & JSXBase.HTMLAttributes<HTMLCoreprojectShapeGiftElement>;
            "coreproject-shape-globe": LocalJSX.CoreprojectShapeGlobe & JSXBase.HTMLAttributes<HTMLCoreprojectShapeGlobeElement>;
            "coreproject-shape-grid": LocalJSX.CoreprojectShapeGrid & JSXBase.HTMLAttributes<HTMLCoreprojectShapeGridElement>;
            "coreproject-shape-hard-drive": LocalJSX.CoreprojectShapeHardDrive & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHardDriveElement>;
            "coreproject-shape-hash": LocalJSX.CoreprojectShapeHash & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHashElement>;
            "coreproject-shape-headphones": LocalJSX.CoreprojectShapeHeadphones & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHeadphonesElement>;
            "coreproject-shape-heart": LocalJSX.CoreprojectShapeHeart & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHeartElement>;
            "coreproject-shape-help-circle": LocalJSX.CoreprojectShapeHelpCircle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHelpCircleElement>;
            "coreproject-shape-home": LocalJSX.CoreprojectShapeHome & JSXBase.HTMLAttributes<HTMLCoreprojectShapeHomeElement>;
            "coreproject-shape-info": LocalJSX.CoreprojectShapeInfo & JSXBase.HTMLAttributes<HTMLCoreprojectShapeInfoElement>;
            "coreproject-shape-key": LocalJSX.CoreprojectShapeKey & JSXBase.HTMLAttributes<HTMLCoreprojectShapeKeyElement>;
            "coreproject-shape-link": LocalJSX.CoreprojectShapeLink & JSXBase.HTMLAttributes<HTMLCoreprojectShapeLinkElement>;
            "coreproject-shape-list": LocalJSX.CoreprojectShapeList & JSXBase.HTMLAttributes<HTMLCoreprojectShapeListElement>;
            "coreproject-shape-lock": LocalJSX.CoreprojectShapeLock & JSXBase.HTMLAttributes<HTMLCoreprojectShapeLockElement>;
            "coreproject-shape-log-in": LocalJSX.CoreprojectShapeLogIn & JSXBase.HTMLAttributes<HTMLCoreprojectShapeLogInElement>;
            "coreproject-shape-log-out": LocalJSX.CoreprojectShapeLogOut & JSXBase.HTMLAttributes<HTMLCoreprojectShapeLogOutElement>;
            "coreproject-shape-logo": LocalJSX.CoreprojectShapeLogo & JSXBase.HTMLAttributes<HTMLCoreprojectShapeLogoElement>;
            "coreproject-shape-mail": LocalJSX.CoreprojectShapeMail & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMailElement>;
            "coreproject-shape-map-pin": LocalJSX.CoreprojectShapeMapPin & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMapPinElement>;
            "coreproject-shape-maximize": LocalJSX.CoreprojectShapeMaximize & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMaximizeElement>;
            "coreproject-shape-meh": LocalJSX.CoreprojectShapeMeh & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMehElement>;
            "coreproject-shape-message-circle": LocalJSX.CoreprojectShapeMessageCircle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMessageCircleElement>;
            "coreproject-shape-minimize": LocalJSX.CoreprojectShapeMinimize & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMinimizeElement>;
            "coreproject-shape-minus": LocalJSX.CoreprojectShapeMinus & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMinusElement>;
            "coreproject-shape-monitor": LocalJSX.CoreprojectShapeMonitor & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMonitorElement>;
            "coreproject-shape-moon": LocalJSX.CoreprojectShapeMoon & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMoonElement>;
            "coreproject-shape-more": LocalJSX.CoreprojectShapeMore & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMoreElement>;
            "coreproject-shape-mouse-pointer": LocalJSX.CoreprojectShapeMousePointer & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMousePointerElement>;
            "coreproject-shape-move": LocalJSX.CoreprojectShapeMove & JSXBase.HTMLAttributes<HTMLCoreprojectShapeMoveElement>;
            "coreproject-shape-pause": LocalJSX.CoreprojectShapePause & JSXBase.HTMLAttributes<HTMLCoreprojectShapePauseElement>;
            "coreproject-shape-pause-circle": LocalJSX.CoreprojectShapePauseCircle & JSXBase.HTMLAttributes<HTMLCoreprojectShapePauseCircleElement>;
            "coreproject-shape-play": LocalJSX.CoreprojectShapePlay & JSXBase.HTMLAttributes<HTMLCoreprojectShapePlayElement>;
            "coreproject-shape-play-circle": LocalJSX.CoreprojectShapePlayCircle & JSXBase.HTMLAttributes<HTMLCoreprojectShapePlayCircleElement>;
            "coreproject-shape-plus": LocalJSX.CoreprojectShapePlus & JSXBase.HTMLAttributes<HTMLCoreprojectShapePlusElement>;
            "coreproject-shape-preferences": LocalJSX.CoreprojectShapePreferences & JSXBase.HTMLAttributes<HTMLCoreprojectShapePreferencesElement>;
            "coreproject-shape-refresh": LocalJSX.CoreprojectShapeRefresh & JSXBase.HTMLAttributes<HTMLCoreprojectShapeRefreshElement>;
            "coreproject-shape-repeat": LocalJSX.CoreprojectShapeRepeat & JSXBase.HTMLAttributes<HTMLCoreprojectShapeRepeatElement>;
            "coreproject-shape-rotate": LocalJSX.CoreprojectShapeRotate & JSXBase.HTMLAttributes<HTMLCoreprojectShapeRotateElement>;
            "coreproject-shape-save": LocalJSX.CoreprojectShapeSave & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSaveElement>;
            "coreproject-shape-search": LocalJSX.CoreprojectShapeSearch & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSearchElement>;
            "coreproject-shape-settings": LocalJSX.CoreprojectShapeSettings & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSettingsElement>;
            "coreproject-shape-share": LocalJSX.CoreprojectShapeShare & JSXBase.HTMLAttributes<HTMLCoreprojectShapeShareElement>;
            "coreproject-shape-shield": LocalJSX.CoreprojectShapeShield & JSXBase.HTMLAttributes<HTMLCoreprojectShapeShieldElement>;
            "coreproject-shape-shopping-cart": LocalJSX.CoreprojectShapeShoppingCart & JSXBase.HTMLAttributes<HTMLCoreprojectShapeShoppingCartElement>;
            "coreproject-shape-shrink": LocalJSX.CoreprojectShapeShrink & JSXBase.HTMLAttributes<HTMLCoreprojectShapeShrinkElement>;
            "coreproject-shape-smartphone": LocalJSX.CoreprojectShapeSmartphone & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSmartphoneElement>;
            "coreproject-shape-smile": LocalJSX.CoreprojectShapeSmile & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSmileElement>;
            "coreproject-shape-speaker": LocalJSX.CoreprojectShapeSpeaker & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSpeakerElement>;
            "coreproject-shape-star": LocalJSX.CoreprojectShapeStar & JSXBase.HTMLAttributes<HTMLCoreprojectShapeStarElement>;
            "coreproject-shape-sun": LocalJSX.CoreprojectShapeSun & JSXBase.HTMLAttributes<HTMLCoreprojectShapeSunElement>;
            "coreproject-shape-tag": LocalJSX.CoreprojectShapeTag & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTagElement>;
            "coreproject-shape-terminal": LocalJSX.CoreprojectShapeTerminal & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTerminalElement>;
            "coreproject-shape-thumbs": LocalJSX.CoreprojectShapeThumbs & JSXBase.HTMLAttributes<HTMLCoreprojectShapeThumbsElement>;
            "coreproject-shape-toggle": LocalJSX.CoreprojectShapeToggle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeToggleElement>;
            "coreproject-shape-tool": LocalJSX.CoreprojectShapeTool & JSXBase.HTMLAttributes<HTMLCoreprojectShapeToolElement>;
            "coreproject-shape-trash": LocalJSX.CoreprojectShapeTrash & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTrashElement>;
            "coreproject-shape-trending": LocalJSX.CoreprojectShapeTrending & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTrendingElement>;
            "coreproject-shape-triangle": LocalJSX.CoreprojectShapeTriangle & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTriangleElement>;
            "coreproject-shape-twitter": LocalJSX.CoreprojectShapeTwitter & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTwitterElement>;
            "coreproject-shape-type": LocalJSX.CoreprojectShapeType & JSXBase.HTMLAttributes<HTMLCoreprojectShapeTypeElement>;
            "coreproject-shape-underline": LocalJSX.CoreprojectShapeUnderline & JSXBase.HTMLAttributes<HTMLCoreprojectShapeUnderlineElement>;
            "coreproject-shape-unlock": LocalJSX.CoreprojectShapeUnlock & JSXBase.HTMLAttributes<HTMLCoreprojectShapeUnlockElement>;
            "coreproject-shape-upload": LocalJSX.CoreprojectShapeUpload & JSXBase.HTMLAttributes<HTMLCoreprojectShapeUploadElement>;
            "coreproject-shape-user": LocalJSX.CoreprojectShapeUser & JSXBase.HTMLAttributes<HTMLCoreprojectShapeUserElement>;
            "coreproject-shape-users": LocalJSX.CoreprojectShapeUsers & JSXBase.HTMLAttributes<HTMLCoreprojectShapeUsersElement>;
            "coreproject-shape-volume": LocalJSX.CoreprojectShapeVolume & JSXBase.HTMLAttributes<HTMLCoreprojectShapeVolumeElement>;
            "coreproject-shape-x": LocalJSX.CoreprojectShapeX & JSXBase.HTMLAttributes<HTMLCoreprojectShapeXElement>;
            "coreproject-shape-zap-off": LocalJSX.CoreprojectShapeZapOff & JSXBase.HTMLAttributes<HTMLCoreprojectShapeZapOffElement>;
            "coreproject-shape-zoom": LocalJSX.CoreprojectShapeZoom & JSXBase.HTMLAttributes<HTMLCoreprojectShapeZoomElement>;
        }
    }
}
