/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreVideoPlayer {
        "magnet": string;
    }
}
declare global {
    interface HTMLCoreVideoPlayerElement extends Components.CoreVideoPlayer, HTMLStencilElement {
    }
    var HTMLCoreVideoPlayerElement: {
        prototype: HTMLCoreVideoPlayerElement;
        new (): HTMLCoreVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "core-video-player": HTMLCoreVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface CoreVideoPlayer {
        "magnet"?: string;
    }
    interface IntrinsicElements {
        "core-video-player": CoreVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-video-player": LocalJSX.CoreVideoPlayer & JSXBase.HTMLAttributes<HTMLCoreVideoPlayerElement>;
        }
    }
}
